apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-mongo-pvc
  namespace: library-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notification-mongo
  namespace: library-system
spec:
  selector:
    matchLabels:
      app: notification-mongo
  serviceName: notification-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: notification-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: notification-mongo-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: notification-mongo-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: notification-mongo
  namespace: library-system
spec:
  ports:
  - port: 27017
  clusterIP: None
  selector:
    app: notification-mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: library-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: notification-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_HOST
          value: notification-mongo.library-system.svc.cluster.local
        - name: MONGO_PORT
          value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: library-system
spec:
  selector:
    app: notification-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP

