apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: report-postgres-pvc
  namespace: library-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: report-postgres
  namespace: library-system
spec:
  selector:
    matchLabels:
      app: report-postgres
  serviceName: report-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: report-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: reportdb
        - name: POSTGRES_USER
          value: reportuser
        - name: POSTGRES_PASSWORD
          value: reportpass123
        volumeMounts:
        - name: report-postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: report-postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: report-postgres
  namespace: library-system
spec:
  ports:
  - port: 5432
  clusterIP: None
  selector:
    app: report-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  namespace: library-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
      - name: report-service
        image: report-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: report-postgres.library-system.svc.cluster.local
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: reportuser
        - name: DB_PASSWORD
          value: reportpass123
        - name: DB_NAME
          value: reportdb
---
apiVersion: v1
kind: Service
metadata:
  name: report-service
  namespace: library-system
spec:
  selector:
    app: report-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP

